'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('lab', {
  // ---- in-game overlay ----
  overlays: () => ipcRenderer.invoke('overlay-list'),
  overlayPreferences: () => ipcRenderer.invoke('overlay-preferences'),
  saveOverlayPreferences: (patch) => ipcRenderer.invoke('overlay-save-preferences', patch),
  overlayAdd: () => ipcRenderer.invoke('overlay-add'),
  overlayRemove: (id) => ipcRenderer.invoke('overlay-remove', id),
  overlayInstall: (id) => ipcRenderer.invoke('overlay-install', id),
  overlayUninstall: (id) => ipcRenderer.invoke('overlay-uninstall', id),
  overlaySource: () => ipcRenderer.invoke('overlay-source'),
  overlayBridge: () => ipcRenderer.invoke('overlay-bridge'),
  checkUpdate: () => ipcRenderer.invoke('update-check'),
  unhide: (dir) => ipcRenderer.invoke('unhide', dir),
  boot: () => ipcRenderer.invoke('boot'),
  setLang: (lang) => ipcRenderer.invoke('set-lang', lang),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  window: (action) => ipcRenderer.invoke('window', action),
  library: () => ipcRenderer.invoke('library'),
  scan: (dir) => ipcRenderer.invoke('scan', dir),
  history: () => ipcRenderer.invoke('history'),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  saveDiagnostics: (dir, activity) => ipcRenderer.invoke('save-diagnostics', dir, activity),
  gameMenu: (dir, options) => ipcRenderer.invoke('game-menu', dir, options),
  communityProfile: () => ipcRenderer.invoke('community-profile'),
  communitySaveProfile: (profile) => ipcRenderer.invoke('community-profile-save', profile),
  communityAdminLogout: () => ipcRenderer.invoke('community-admin-logout'),
  communityDeleteMe: () => ipcRenderer.invoke('community-delete-me'),
  communityCards: (filters) => ipcRenderer.invoke('community-cards', filters),
  communityMyReports: () => ipcRenderer.invoke('community-my-reports'),
  communityCard: (key, etag, fresh) => ipcRenderer.invoke('community-card', key, etag, fresh),
  communityUpdates: (key, since, etag) => ipcRenderer.invoke('community-updates', key, since, etag),
  communityPrefill: (dir) => ipcRenderer.invoke('community-prefill', dir),
  communityReport: (report) => ipcRenderer.invoke('community-report', report),
  communityWithdraw: (id) => ipcRenderer.invoke('community-withdraw', id),
  communityWithdrawReply: (id) => ipcRenderer.invoke('community-withdraw-reply', id),
  communityReaction: (id, emoji, on) => ipcRenderer.invoke('community-reaction', id, emoji, on),
  communityAdminModerate: (kind, id, action) => ipcRenderer.invoke('community-admin-moderate', kind, id, action),
  communityChatFeed: (options) => ipcRenderer.invoke('community-chat-feed', options),
  communityChatPeople: () => ipcRenderer.invoke('community-chat-people'),
  communityChatMe: () => ipcRenderer.invoke('community-chat-me'),
  communityChatUpload: (meta, bytes) => ipcRenderer.invoke('community-chat-upload', meta, bytes),
  communityChatPost: (input) => ipcRenderer.invoke('community-chat-post', input),
  communityChatEdit: (id, body) => ipcRenderer.invoke('community-chat-edit', id, body),
  communityChatDelete: (id) => ipcRenderer.invoke('community-chat-delete', id),
  communityChatReaction: (id, emoji, on) => ipcRenderer.invoke('community-chat-reaction', id, emoji, on),
  communityChatModerate: (id, action) => ipcRenderer.invoke('community-chat-moderate', id, action),
  communityChatSaveImage: (url, name) => ipcRenderer.invoke('community-chat-save-image', url, name),
  settings: () => ipcRenderer.invoke('settings'),
  setGroupGamesByStore: (enabled) => ipcRenderer.invoke('set-group-games-by-store', enabled),
  setCloseToTray: (enabled) => ipcRenderer.invoke('set-close-to-tray', enabled),
  driverNeuralFault: () => ipcRenderer.invoke('driver-neural-fault'),
  optiscalerBuilds: (dir) => ipcRenderer.invoke('optiscaler-builds', dir),
  setOptiscalerBuild: (dir, version) => ipcRenderer.invoke('set-optiscaler-build', dir, version),
  acknowledgeDriver: (names) => ipcRenderer.invoke('acknowledge-driver', names),
  setTrayLabels: (labels) => ipcRenderer.invoke('set-tray-labels', labels),
  setAutoScanDrives: (enabled) => ipcRenderer.invoke('set-auto-scan-drives', enabled),
  addFolder: () => ipcRenderer.invoke('add-folder'),
  removeFolder: (dir) => ipcRenderer.invoke('remove-folder', dir),
  excludeRoot: (dir) => ipcRenderer.invoke('exclude-root', dir),
  addGame: () => ipcRenderer.invoke('add-game'),
  addGameByPath: (dir) => ipcRenderer.invoke('add-game-path', dir),
  setPoster: (dir) => ipcRenderer.invoke('set-poster', dir),
  hide: (dir) => ipcRenderer.invoke('hide', dir),
  reset: () => ipcRenderer.invoke('reset'),
  open: (dir) => ipcRenderer.invoke('open', dir),
  openProject: (destination) => ipcRenderer.invoke('open-project', destination),
  setApiOverride: (dir, exePath, value) => ipcRenderer.invoke('set-api-override', dir, exePath, value),
  artStatus: () => ipcRenderer.invoke('art-status'),
  artFetch: (dir, name, appid) => ipcRenderer.invoke('art-fetch', dir, name, appid),
  communityArt: (key, title) => ipcRenderer.invoke('community-art', key, title),
  // The renderer reuses pixels from the image it has already displayed. Only
  // a 12×12 RGBA thumbnail crosses this boundary; there is no second download.
  communityPalette: (pixels) => ipcRenderer.invoke('community-palette', pixels),
  communityMergePalettes: (palettes) => ipcRenderer.invoke('community-palette-merge', palettes),
  communityReplies: (id, fresh) => ipcRenderer.invoke('community-replies', id, fresh),
  communityReply: (id, body, mentions) => ipcRenderer.invoke('community-reply', id, body, mentions),
  communityEditReply: (id, body) => ipcRenderer.invoke('community-edit-reply', id, body),
  communityFollow: (key, on) => ipcRenderer.invoke('community-follow', key, on),
  communityNotices: () => ipcRenderer.invoke('community-notices'),
  communityNotify: (items) => ipcRenderer.invoke('community-notify', items),
  communityNoticesRead: () => ipcRenderer.invoke('community-notices-read'),
  communityNoticeSettings: (on) => ipcRenderer.invoke('community-notice-settings', on),
  onCommunityNotices: (fn) => ipcRenderer.on('community-notices', (_e, list) => fn(list)),
  onCommunityOpen: (fn) => ipcRenderer.on('community-open', (_e, notice) => fn(notice)),
  touch: (dir) => ipcRenderer.invoke('touch', dir),
  recents: () => ipcRenderer.invoke('recents'),
  details: (dir) => ipcRenderer.invoke('details', dir),
  install: (dir, exePath, route, api) => ipcRenderer.invoke('install', dir, exePath, route, api),
  addons: () => ipcRenderer.invoke('addons'),
  addonToggle: (file, on) => ipcRenderer.invoke('addon-toggle', file, on),
  addonPick: () => ipcRenderer.invoke('addon-pick'),
  addonSave: (entry) => ipcRenderer.invoke('addon-save', entry),
  addonRemove: (file) => ipcRenderer.invoke('addon-remove', file),
  restoreGame: (dir) => ipcRenderer.invoke('restore', dir),
  onJob: (handler) => ipcRenderer.on('job', (_e, event) => handler(event)),
  pathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return null; } },
  checkForUpdates: () => ipcRenderer.invoke('updater-check'),
  startUpdateDownload: () => ipcRenderer.invoke('updater-download'),
  installUpdate: () => ipcRenderer.invoke('updater-install'),
  cancelUpdateDownload: () => ipcRenderer.invoke('updater-cancel'),
  getUpdateStatus: () => ipcRenderer.invoke('updater-status'),
  setAutoCheckUpdates: (enabled) => ipcRenderer.invoke('set-auto-check-updates', enabled),
  onUpdaterEvent: (handler) => {
    const fn = (_e, data) => handler(data);
    ipcRenderer.on('updater-event', fn);
    return () => ipcRenderer.removeListener('updater-event', fn);
  },
  onUpdaterProgress: (handler) => {
    const fn = (_e, data) => handler(data);
    ipcRenderer.on('updater-progress', fn);
    return () => ipcRenderer.removeListener('updater-progress', fn);
  }
});
